(() => {
  "use strict";

  const topic = (id, name, initialStatus = "not-started") => ({
    id,
    name,
    initialStatus,
  });

  const block = (id, name, topics, options = {}) => ({ id, name, topics, ...options });

  const subjects = [
    {
      id: "matematica",
      name: "Matemática",
      shortName: "Matemática",
      mark: "M",
      description: "Raciocínio, álgebra, geometria e tratamento da informação.",
      blocks: [
        block("mat-numeros-operacoes", "Números e Operações", [
          topic("operacoes", "Operações", "mastered"),
          topic("fracoes", "Frações", "mastered"),
          topic("numeros-decimais", "Números decimais", "mastered"),
          topic("porcentagem", "Porcentagem", "mastered"),
          topic("razao", "Razão", "mastered"),
          topic("proporcao", "Proporção", "mastered"),
        ]),
        block("mat-algebra", "Álgebra", [
          topic("equacoes", "Equações", "mastered"),
          topic("sistemas", "Sistemas", "mastered"),
          topic("produtos-notaveis", "Produtos notáveis", "mastered"),
          topic("fatoracao", "Fatoração"),
          topic("potenciacao", "Potenciação"),
          topic("radiciacao", "Radiciação"),
          topic("expressoes-polinomios", "Expressões algébricas e polinômios"),
          topic("inequacoes", "Inequações"),
          topic("equacao-segundo-grau", "Equação do 2º grau"),
        ]),
        block("mat-geometria", "Geometria", [
          topic("angulos", "Ângulos"),
          topic("triangulos", "Triângulos"),
          topic("poligonos", "Quadriláteros e polígonos"),
          topic("perimetro-area", "Perímetro e área"),
          topic("teorema-pitagoras", "Teorema de Pitágoras"),
          topic("semelhanca", "Semelhança"),
          topic("circunferencia", "Circunferência e círculo"),
          topic("geometria-espacial-volume", "Geometria espacial e volume"),
        ]),
        block("mat-informacao", "Tratamento da informação", [
          topic("tabelas-graficos", "Tabelas e gráficos"),
          topic("media-moda-mediana", "Média, moda e mediana"),
          topic("probabilidade", "Probabilidade"),
        ]),
      ],
    },
    {
      id: "portugues",
      name: "Português",
      shortName: "Português",
      mark: "P",
      description: "Interpretação, gêneros e gramática aplicada à prova.",
      blocks: [
        block("pt-interpretacao", "Interpretação textual", [
          topic("pt-tema-ideia", "Tema, assunto e ideia principal"),
          topic("pt-explicitas-implicitas", "Informações explícitas e implícitas"),
          topic("pt-inferencia", "Inferência"),
          topic("pt-finalidade-ponto-vista", "Finalidade e ponto de vista"),
          topic("pt-ironia-humor-ambiguidade", "Ironia, humor e ambiguidade"),
          topic("pt-intertextualidade", "Intertextualidade"),
        ]),
        block("pt-generos", "Gêneros textuais", [
          topic("pt-noticia-reportagem", "Notícia e reportagem"),
          topic("pt-artigo-opiniao", "Artigo de opinião"),
          topic("pt-cronica-conto", "Crônica e conto"),
          topic("pt-poema", "Poema"),
          topic("pt-charge-tirinha-propaganda", "Charge, tirinha e propaganda"),
          topic("pt-divulgacao-cientifica", "Texto de divulgação científica"),
        ]),
        block("pt-gramatica", "Gramática aplicada", [
          topic("pt-classes-palavras", "Classes de palavras"),
          topic("pt-verbos", "Verbos"),
          topic("pt-frase-oracao-periodo", "Frase, oração e período"),
          topic("pt-sujeito-predicado", "Sujeito e predicado"),
          topic("pt-coordenacao-subordinacao", "Coordenação e subordinação"),
          topic("pt-concordancia", "Concordância"),
          topic("pt-pontuacao", "Pontuação"),
        ]),
        block("pt-linguagem", "Linguagem", [
          topic("pt-denotacao-conotacao", "Denotação e conotação"),
          topic("pt-figuras-linguagem", "Figuras de linguagem"),
          topic("pt-coesao-coerencia", "Coesão e coerência"),
          topic("pt-variacao-linguistica", "Variação linguística"),
        ]),
      ],
    },
    {
      id: "ciencias",
      name: "Ciências",
      shortName: "Ciências",
      mark: "C",
      description: "Matéria, energia, vida e ecologia em uma visão integrada.",
      blocks: [
        block("cie-materia", "Matéria", [
          topic("cie-materia-corpo-objeto", "Matéria, corpo e objeto"),
          topic("cie-estados-fisicos", "Estados físicos da matéria"),
          topic("cie-mudancas-estado", "Mudanças de estado"),
          topic("cie-propriedades-materia", "Propriedades da matéria"),
          topic("cie-substancias-misturas", "Substâncias e misturas"),
          topic("cie-separacao-misturas", "Separação de misturas"),
        ]),
        block("cie-estrutura", "Estrutura da matéria", [
          topic("cie-atomos", "Átomos"),
          topic("cie-particulas-atomo", "Prótons, elétrons e nêutrons"),
          topic("cie-elementos-quimicos", "Elementos químicos"),
          topic("cie-moleculas", "Moléculas"),
          topic("cie-tabela-periodica", "Tabela periódica — fundamentos"),
          topic("cie-transformacoes", "Transformações físicas e químicas"),
        ]),
        block("cie-fisica-energia", "Física e energia", [
          topic("cie-movimento-repouso", "Movimento e repouso"),
          topic("cie-velocidade-media", "Velocidade média"),
          topic("cie-forca", "Força"),
          topic("cie-massa-peso", "Massa e peso"),
          topic("cie-gravidade", "Gravidade"),
          topic("cie-trabalho-energia", "Trabalho e energia"),
          topic("cie-calor-temperatura", "Calor e temperatura"),
          topic("cie-ondas-som", "Ondas e som"),
          topic("cie-luz-optica", "Luz e óptica"),
          topic("cie-eletricidade", "Eletricidade básica"),
        ]),
        block("cie-vida", "Vida", [
          topic("cie-celula", "Célula"),
          topic("cie-celula-animal-vegetal", "Célula animal e vegetal"),
          topic("cie-tecidos-orgaos-sistemas", "Tecidos, órgãos e sistemas"),
          topic("cie-sistema-digestorio", "Sistema digestório"),
          topic("cie-sistema-respiratorio", "Sistema respiratório"),
          topic("cie-sistema-circulatorio", "Sistema circulatório"),
          topic("cie-sistema-nervoso", "Sistema nervoso"),
          topic("cie-reproducao", "Reprodução"),
          topic("cie-genetica", "Genética básica"),
          topic("cie-evolucao", "Evolução"),
        ]),
        block("cie-ecologia", "Ecologia", [
          topic("cie-ecossistemas", "Ecossistemas"),
          topic("cie-habitat-nicho", "Habitat e nicho"),
          topic("cie-cadeias-teias", "Cadeias e teias alimentares"),
          topic("cie-relacoes-ecologicas", "Relações ecológicas"),
          topic("cie-biomas-brasileiros", "Biomas brasileiros"),
          topic("cie-impactos-ambientais", "Impactos ambientais"),
          topic("cie-mudancas-climaticas", "Mudanças climáticas"),
        ]),
      ],
    },
    {
      id: "historia",
      name: "História",
      shortName: "História",
      mark: "H",
      chronology: true,
      description: "Cronologia, contexto e relações de causa e consequência.",
      blocks: [
        block("his-fundamentos", "Fundamentos", [
          topic("his-o-que-e", "O que é História"),
          topic("his-fontes", "Fontes históricas"),
          topic("his-tempo", "Tempo histórico"),
          topic("his-pre-historia", "Pré-História"),
        ], { period: "Origens" }),
        block("his-antiguidade", "Antiguidade", [
          topic("his-mesopotamia", "Mesopotâmia"),
          topic("his-egito", "Egito"),
          topic("his-grecia", "Grécia"),
          topic("his-roma", "Roma"),
        ], { period: "c. 3500 a.C. — 476" }),
        block("his-idade-media", "Idade Média", [
          topic("his-feudalismo", "Feudalismo"),
          topic("his-igreja-medieval", "Igreja medieval"),
          topic("his-cruzadas", "Cruzadas"),
          topic("his-crescimento-cidades", "Crescimento das cidades"),
        ], { period: "476 — 1453" }),
        block("his-idade-moderna", "Idade Moderna", [
          topic("his-renascimento", "Renascimento"),
          topic("his-reformas-religiosas", "Reformas religiosas"),
          topic("his-absolutismo", "Absolutismo"),
          topic("his-mercantilismo", "Mercantilismo"),
          topic("his-expansao-maritima", "Expansão marítima"),
          topic("his-colonizacao-americas", "Colonização das Américas"),
          topic("his-iluminismo", "Iluminismo"),
        ], { period: "séculos XV — XVIII" }),
        block("his-revolucoes", "Revoluções", [
          topic("his-revolucao-industrial", "Revolução Industrial"),
          topic("his-independencia-eua", "Independência dos EUA"),
          topic("his-revolucao-francesa", "Revolução Francesa"),
          topic("his-era-napoleonica", "Era Napoleônica"),
        ], { period: "séculos XVIII — XIX" }),
        block("his-contemporaneo", "Mundo Contemporâneo", [
          topic("his-imperialismo", "Imperialismo"),
          topic("his-primeira-guerra", "Primeira Guerra Mundial"),
          topic("his-revolucao-russa", "Revolução Russa"),
          topic("his-crise-1929", "Crise de 1929"),
          topic("his-fascismo-nazismo", "Fascismo e nazismo"),
          topic("his-segunda-guerra", "Segunda Guerra Mundial"),
          topic("his-guerra-fria", "Guerra Fria"),
          topic("his-descolonizacao", "Descolonização"),
          topic("his-pos-guerra-fria", "Mundo pós-Guerra Fria"),
        ], { period: "séculos XIX — XXI" }),
        block("his-brasil-colonial", "Brasil Colonial", [
          topic("his-povos-indigenas", "Povos indígenas antes da colonização"),
          topic("his-colonizacao-portuguesa", "Colonização portuguesa"),
          topic("his-acucar-escravidao", "Açúcar e escravidão"),
          topic("his-bandeirantes", "Bandeirantes"),
          topic("his-mineracao", "Mineração"),
          topic("his-revoltas-coloniais", "Revoltas coloniais"),
        ], { period: "1500 — 1822", group: "História do Brasil" }),
        block("his-brasil-imperio", "Brasil Império", [
          topic("his-familia-real", "Família Real no Brasil"),
          topic("his-independencia-brasil", "Independência"),
          topic("his-primeiro-reinado", "Primeiro Reinado"),
          topic("his-periodo-regencial", "Período Regencial"),
          topic("his-segundo-reinado", "Segundo Reinado"),
          topic("his-cafe-escravidao", "Café e escravidão"),
          topic("his-abolicao", "Abolição"),
        ], { period: "1808 — 1889", group: "História do Brasil" }),
        block("his-brasil-republica", "Brasil República", [
          topic("his-proclamacao-republica", "Proclamação da República"),
          topic("his-republica-espada", "República da Espada"),
          topic("his-republica-oligarquica", "República Oligárquica"),
          topic("his-coronelismo", "Coronelismo"),
          topic("his-era-vargas", "Era Vargas"),
          topic("his-republica-1946", "República de 1946"),
          topic("his-ditadura-militar", "Ditadura militar"),
          topic("his-redemocratizacao", "Redemocratização"),
          topic("his-constituicao-1988", "Constituição de 1988"),
        ], { period: "1889 — atualidade", group: "História do Brasil" }),
      ],
    },
    {
      id: "geografia",
      name: "Geografia",
      shortName: "Geografia",
      mark: "G",
      description: "Espaço, território, natureza, sociedade e mundo contemporâneo.",
      blocks: [
        block("geo-fundamentos", "Fundamentos", [
          topic("geo-espaco-geografico", "Espaço geográfico"),
          topic("geo-paisagem", "Paisagem"),
          topic("geo-lugar", "Lugar"),
          topic("geo-territorio", "Território"),
          topic("geo-regiao", "Região"),
        ]),
        block("geo-cartografia", "Cartografia", [
          topic("geo-orientacao", "Orientação"),
          topic("geo-pontos-cardeais", "Pontos cardeais"),
          topic("geo-latitude-longitude", "Latitude e longitude"),
          topic("geo-coordenadas", "Coordenadas geográficas"),
          topic("geo-mapas", "Mapas"),
          topic("geo-escalas", "Escalas"),
          topic("geo-fusos", "Fusos horários"),
          topic("geo-projecoes", "Projeções cartográficas"),
        ]),
        block("geo-fisica", "Geografia física", [
          topic("geo-estrutura-terra", "Estrutura interna da Terra"),
          topic("geo-placas-tectonicas", "Placas tectônicas"),
          topic("geo-relevo", "Relevo"),
          topic("geo-rochas-solos", "Rochas e solos"),
          topic("geo-atmosfera", "Atmosfera"),
          topic("geo-tempo-clima", "Tempo e clima"),
          topic("geo-climas-brasileiros", "Climas brasileiros"),
          topic("geo-hidrografia", "Hidrografia"),
          topic("geo-vegetacao", "Vegetação"),
          topic("geo-biomas-brasileiros", "Biomas brasileiros"),
        ]),
        block("geo-populacao", "População", [
          topic("geo-populacao-absoluta-relativa", "População absoluta e relativa"),
          topic("geo-densidade", "Densidade demográfica"),
          topic("geo-crescimento-populacional", "Crescimento populacional"),
          topic("geo-natalidade-mortalidade", "Natalidade e mortalidade"),
          topic("geo-migracoes", "Migrações"),
          topic("geo-piramides-etarias", "Pirâmides etárias"),
          topic("geo-urbanizacao", "Urbanização"),
        ]),
        block("geo-economia", "Geografia econômica", [
          topic("geo-agricultura", "Agricultura"),
          topic("geo-pecuaria", "Pecuária"),
          topic("geo-extrativismo", "Extrativismo"),
          topic("geo-industrializacao", "Industrialização"),
          topic("geo-comercio-servicos", "Comércio e serviços"),
          topic("geo-fontes-energia", "Fontes de energia"),
          topic("geo-transportes", "Transportes"),
        ]),
        block("geo-brasil", "Brasil", [
          topic("geo-regionalizacao-brasileira", "Regionalização brasileira"),
          topic("geo-regioes-brasil", "Regiões do Brasil"),
          topic("geo-industrializacao-brasileira", "Industrialização brasileira"),
          topic("geo-urbanizacao-brasileira", "Urbanização brasileira"),
          topic("geo-agropecuaria-brasileira", "Agropecuária brasileira"),
          topic("geo-desigualdades-regionais", "Desigualdades regionais"),
        ]),
        block("geo-mundo", "Mundo contemporâneo", [
          topic("geo-globalizacao", "Globalização"),
          topic("geo-capitalismo", "Capitalismo"),
          topic("geo-blocos-economicos", "Blocos econômicos"),
          topic("geo-desenvolvimento", "Países desenvolvidos e em desenvolvimento"),
          topic("geo-geopolitica", "Geopolítica"),
          topic("geo-migracoes-internacionais", "Migrações internacionais"),
          topic("geo-problemas-ambientais", "Problemas ambientais globais"),
        ]),
      ],
    },
  ];

  const schedule = {
    0: { type: "weekly-review", label: "Revisão semanal flexível" },
    1: { primary: { subjectId: "matematica", minutes: 50 }, secondary: { subjectId: "historia", minutes: 30 } },
    2: { primary: { subjectId: "ciencias", minutes: 50 }, secondary: { subjectId: "matematica", minutes: 30 } },
    3: { primary: { subjectId: "matematica", minutes: 50 }, secondary: { subjectId: "geografia", minutes: 30 } },
    4: { primary: { subjectId: "historia", minutes: 50 }, secondary: { subjectId: "matematica", minutes: 30 } },
    5: { primary: { subjectId: "matematica", minutes: 50 }, secondary: { subjectId: "portugues", minutes: 30 } },
    6: { type: "weekly-review", label: "Revisão semanal flexível" },
  };

  window.TRAJETORIA_DATA = { subjects, schedule };
})();
